### ISSUE TITLE
error updating the db: "no such column: mask"

### ISSUE THREAD

**Issue by bnord** [linea-it/masterlist#3]
The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Mon Jul 25 09:09:24 2016 from mac-124358.dhcp.fnal.gov

= Updating the code =
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/linea-it/masterlist
   5ab0cef..ea3e6d5  master     -> origin/master
Updating 5ab0cef..ea3e6d5
Fast-forward
 masterlist/candidates/models.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

= Updating the images =
Already up-to-date.

= Setting up env =

= Updating requirements =
Requirement already up-to-date: Django==1.8.4 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 1))
Requirement already up-to-date: Markdown==2.6.2 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 2))
Requirement already up-to-date: django-filter==0.10.0 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 3))
Requirement already up-to-date: djangorestframework==3.1.3 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 4))
Requirement already up-to-date: django-tables2==1.2.1 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 5))
Requirement already up-to-date: pytest==2.8.7 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 6))
Requirement already up-to-date: requests==2.9.1 in ./env/lib/python3.4/site-packages (from -r requirements.txt (line 7))
Cleaning up...

= Entering in the application folder =

= Updating the database structure =
Operations to perform:
  Synchronize unmigrated apps: rest_framework, staticfiles, messages, django_tables2
  Apply all migrations: sessions, contenttypes, authtoken, admin, candidates, auth
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.

= Importing the database data =
/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/core/management/commands/loaddata.py:229: RemovedInDjango19Warning: initial_data fixtures are deprecated. Use data migrations instead.
  RemovedInDjango19Warning

Traceback (most recent call last):
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: mask

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/core/management/**init**.py", line 338, in execute_from_command_line
    utility.execute()
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/core/management/**init**.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(_args, *_cmd_options)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(_args, *_options)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
    self.load_label(fixture_label)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 147, in load_label
    obj.save(using=self.using)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/models/base.py", line 762, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/models/base.py", line 827, in _save_table
    forced_update)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/models/base.py", line 877, in _do_update
    return filtered._update(values) > 0
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/srv/domain/desportal.cosmology.illinois.edu/env/lib/python3.4/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: Problem installing fixture '/srv/domain/desportal.cosmology.illinois.edu/masterlist/candidates/fixtures/initial_data.json': Could not load candidates.Candidate(pk=1): no such column: mask
Error, exit
logout
Connection to desportal.cosmology.illinois.edu closed.

**Comment by bnord** [comment]
I tried getting rid of the mask column. It then has trouble with all the new columns that I've added (which are after mask in the list). I'm guessing we need to update hte apache db?

**Comment by bnord** [comment]
@campisano 

┌(nord@mac-124358)─(✓)─(12:52 PM Mon Jul 25)
└─(~/Projects/masterlist/masterlist)─(>)─ ls
candidates/     manage.py\*      masterlist/     run.sh\*         static/

┌(nord@mac-124358)─(✓)─(12:52 PM Mon Jul 25)
└─(~/Projects/masterlist/masterlist)─(>)─ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/nord/anaconda/lib/python2.7/site-packages/django/core/management/**init**.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/nord/anaconda/lib/python2.7/site-packages/django/core/management/**init**.py", line 327, in execute
    django.setup()
  File "/Users/nord/anaconda/lib/python2.7/site-packages/django/**init**.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/nord/anaconda/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/nord/anaconda/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/nord/anaconda/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
ImportError: No module named rest_framework

**Comment by bnord** [comment]
spotted the problem. 
now fixing.

**Comment by bnord** [comment]
had to make sure I'm running with all the packages installed, which means doing the virtual environment. 

Python manage.py makemigrations workign now

**Comment by bnord** [comment]
update successful

**Comment by campisano** [comment]
nice. the update.sh script use virtualenv too.

**Comment by campisano** [comment]
Apparently, it needs of a apache reload. I will investigate a way to do the reload inside the update.sh script. I did it manually just now.
